language: php

sudo: false

php:
    - 5.5
    - 5.6
    - 7.0

#env:
#    global:
#        - secure: ""

install:
    - composer self-update
#    - sh -c "if $TRAVIS_SECURE_ENV_VARS; then composer config --global github-oauth.github.com $GITHUB_OAUTH_TOKEN; fi"
    - composer install

script:
    - find src -name '*.php' -exec php -d display_errors=1 -l {} \;
    - php bin/console lint:twig src
    - php vendor/bin/phpunit --coverage-text
    - php vendor/bin/phpcs src
    - php vendor/bin/phpcs tests
    - php vendor/bin/phpcs app --ignore=app/cache
